name: Build MinGW-w64 Toolchain

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Build:
    runs-on: ubuntu-24.04
    #container: ubuntu:devel
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Set up dependencies
      run: |
        apt-get update
        apt-get install -y g++ flex bison git m4 bzip2 curl make diffutils ninja-build texinfo zip

    - name: Run build script
      env:
        ROOT_PATH: ${{ github.workspace }}/mingw-w64
      run: |
        chmod +x ./build_mingw_w64.sh
        ROOT_PATH=${{ github.workspace }}/mingw-w64 ./build_mingw_w64.sh  x86_64
  
    #- name: zip
    #  if: success()
    #  run: |
    #    cd ${{ github.workspace }}/mingw-w64/x86_64
    #    zip -r mingw-w64-x86_64-toolchain.zip *

    - name: Archive mingw-w64-x86_64-toolchain.zip
      uses: actions/upload-artifact@v4
      with:
        name: mingw-w64-x86_64-toolchain
        path: ${{ github.workspace }}/mingw-w64/x86_64/
    - name: download mingw-w64-x86_64-toolchain.zip
      uses: actions/download-artifact@v4
      with:
        name: download mingw-w64-x86_64-toolchain
        path: ${{ github.workspace }}/mingw-w64/x86_64/
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: mingw-w64
        allowUpdates: true
        artifacts: "${{ github.workspace }}/mingw-w64/x86_64/mingw-w64-x86_64-toolchain.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
