name: Build MinGW-w64 Toolchain

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ flex bison git m4 bzip2 curl make diffutils ninja-build
    - name: 下载测试
      run: |
        mkdir -p ${{ github.workspace }}/xxx
        curl -SLf -o "/tmp/mingw-w64-x86_64-toolchain.gz" "https://github.com/rzhy1/build-mingw-w64/releases/download/mingw-w64/mingw-w64-x86_64-toolchain.gz"
        gzip -dc "/tmp/mingw-w64-x86_64-toolchain.gz" | tar -xf - -C "${{ github.workspace }}/xxx"
        cd ${{ github.workspace }}/xxx
        timestamp=$(date +%s)
        time tar -cf - --exclude=mingw-w64-x86_64-toolchain.gz * | pigz -c > "mingw-w64-x86_64-toolchain-pigz-$timestamp.gz"
        #time tar -cf - --exclude=mingw-w64-x86_64-toolchain.gz * | zstd -T0 > "mingw-w64-x86_64-toolchain-zstd-$timestamp.zst"
        #time tar -czf "mingw-w64-x86_64-toolchain-gzip-$timestamp.gz" --exclude=mingw-w64-x86_64-toolchain.gz *

    - name: Run build script
      env:
        ROOT_PATH: ${{ github.workspace }}/mingw-w64
      run: |
        pigz --version
        chmod +x ./build_mingw_w64.sh
        ROOT_PATH=${{ github.workspace }}/mingw-w64 ./build_mingw_w64.sh  x86_64
  
    - name: zip
      if: success()
      run: |
        cd ${{ github.workspace }}/mingw-w64/x86_64
        tar -cf - * | pigz -c > mingw-w64-x86_64-toolchain.gz
        time tar -cf - --exclude=mingw-w64-x86_64-toolchain.gz * | pigz -9 -p 8 -c > mingw-w64-x86_64-toolchain.gz
        time tar -cf - --exclude=mingw-w64-x86_64-toolchain.gz * | zstd -T0 > mingw-w64-x86_64-toolchain.gz
        time tar -czf mingw-w64-x86_64-toolchain.gz --exclude=mingw-w64-x86_64-toolchain.gz *

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: mingw-w64
        allowUpdates: true
        artifacts: "${{ github.workspace }}/mingw-w64/x86_64/mingw-w64-x86_64-toolchain.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
