name: Build MinGW-w64 Toolchain

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ flex bison git m4 bzip2 curl make diffutils
        
    - name: Cache build dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/mingw-w64/src
          ${{ github.workspace }}/mingw-w64/bld
        key: Linux-mingw-w64-${{ runner.os }}-${{ hashFiles('**/build_mingw_w64.sh') }}
        restore-keys: |
          Linux-mingw-w64-${{ runner.os }}-

    - name: Run build script
      env:
        ROOT_PATH: ${{ github.workspace }}/mingw-w64
        MINGW_W64_BRANCH: "master"
        BINUTILS_BRANCH: "binutils-2_42-branch"
        GCC_BRANCH: "releases/gcc-14"
      run: |
        chmod +x ./build_mingw_w64.sh
        ROOT_PATH=${{ github.workspace }}/mingw-w64 ./build_mingw_w64.sh x86_64

    - name: Archive build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: mingw-w64-x86_64-toolchain
        path: ${{ github.workspace }}/mingw-w64/x86_64
    - name: zip
      if: success()
      run: |
        cd ${{ github.workspace }}/mingw-w64/x86_64
        zip -r mingw-w64-x86_64-toolchain.zip *

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: mingw-w64
        allowUpdates: true
        artifacts: "mingw-w64-x86_64-toolchain.zip,${{ github.workspace }}/mingw-w64/mingw-w64-x86_64-toolchain.zip,${{ github.workspace }}/mingw-w64/x86_64/mingw-w64-x86_64-toolchain.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
