name: Build MinGW-w64 Toolchain

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ flex bison git m4 bzip2 curl make diffutils ninja-build ccache
      
    # 恢复 ccache 缓存
    - name: Cache ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ccache-${{ runner.os }}-mingw-w64-${{ hashFiles('**/Makefile', '**/*.c', '**/*.cpp', '**/*.h') }}
        restore-keys: |
          ccache-${{ runner.os }}-mingw-w64-
          ccache-${{ runner.os }}-

    # 设置 ccache 环境变量
    - name: Set up ccache
      run: |
        export PATH="/usr/lib/ccache:$PATH"
        export CCACHE_DIR="$HOME/.ccache"
        export CCACHE_NOHASHDIR=true
        export CCACHE_SLOPPINESS="file_macro,include_file_ctime,include_file_mtime,time_macros"
        export CCACHE_BASEDIR="$GITHUB_WORKSPACE"
        ccache --max-size=5G
        ccache -z  # 重置 ccache 统计数据

    # 恢复构建缓存
    - name: Cache build dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/mingw-w64/src
          ${{ github.workspace }}/mingw-w64/bld
        key: build-${{ runner.os }}-mingw-w64-${{ hashFiles('**/Makefile', '**/*.c', '**/*.cpp', '**/*.h', '**/*.sh') }}
        restore-keys: |
          build-${{ runner.os }}-mingw-w64-
          build-${{ runner.os }}-

    - name: Run build script
      env:
        ROOT_PATH: ${{ github.workspace }}/mingw-w64
      run: |
        chmod +x ./build_mingw_w64.sh
        ROOT_PATH=${{ github.workspace }}/mingw-w64 ./build_mingw_w64.sh  --keep-artifacts  x86_64
    
    - name: zip
      if: success()
      run: |
        cd ${{ github.workspace }}/mingw-w64/x86_64
        zip -r mingw-w64-x86_64-toolchain.zip *

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: mingw-w64
        allowUpdates: true
        artifacts: "${{ github.workspace }}/mingw-w64/x86_64/mingw-w64-x86_64-toolchain.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Show ccache stats
      run: ccache -s -v
