name: Build MinGW-w64 Toolchain

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ flex bison git m4 bzip2 curl make diffutils ninja-build

    - name: Run build script
      env:
        ROOT_PATH: ${{ github.workspace }}/mingw-w64
      run: |
        pigz --version
        chmod +x ./build_mingw_w64.sh
        ROOT_PATH=${{ github.workspace }}/mingw-w64 ./build_mingw_w64.sh  x86_64
  
    - name: zip
      if: success()
      run: |
        cd ${{ github.workspace }}/mingw-w64/x86_64
        #zip -rq mingw-w64-x86_64-toolchain.zip *
        tar -cf - * | pigz -c > mingw-w64-x86_64-toolchain.gz || { echo "Failed to create or compress the archive"; exit 1; }

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: mingw-w64
        allowUpdates: true
        artifacts: "${{ github.workspace }}/mingw-w64/x86_64/mingw-w64-x86_64-toolchain.lz4"
        token: ${{ secrets.GITHUB_TOKEN }}
