name: Build MinGW-w64 Toolchain

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ flex bison git m4 bzip2 curl make diffutils
        
    - name: Cache build dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/mingw-w64/src
          ${{ github.workspace }}/mingw-w64/bld
        key: ${{ runner.os }}-mingw-w64-${{ hashFiles('**/build_mingw_w64.sh') }}
        restore-keys: |
          ${{ runner.os }}-mingw-w64-

    - name: Run build script
      env:
        ROOT_PATH: ${{ github.workspace }}/mingw-w64
        MINGW_W64_BRANCH: "master"
        BINUTILS_BRANCH: "binutils-2_42-branch"
        GCC_BRANCH: "releases/gcc-14"
      run: |
        chmod +x ./build_mingw_w64.sh
        ./build_mingw_w64.sh x86_64

    - name: Archive build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: mingw-w64-x86_64-toolchain
        path: ${{ github.workspace }}/mingw-w64/x86_64
